### ISSUE TITLE
Column bar truncating...

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [Taiko2k/TauonMusicBox#138]
...pretty much destroyed columns view. One-third of my horizontal space in playlist is now being truncated. Adding and removing columns doesn't work properly anymore, too, because columns get stuck in the truncated area.

Had to go back to this point to make it work again: https://github.com/Taiko2k/TauonMusicBox/tree/f710376f20dbfa12361f55ac0faf16b6a5216ee0

**Comment by Taiko2k** [comment]
I ran into this problem too, but have been having trouble replicating it again. Try the latest commit, if it happens again, could you show me a screenshot, that might he helpful.

**Comment by StrangeSeasOfThought** [comment]
After latest commit:

![bar1](https://user-images.githubusercontent.com/43582772/60159314-2da2c580-97f3-11e9-89ad-ebb9d1747a01.png)

![bar2](https://user-images.githubusercontent.com/43582772/60159320-309db600-97f3-11e9-9de3-332934aabc14.png)

**Comment by StrangeSeasOfThought** [comment]
> -Fixed column to bar possibly rendering over into gallery area
This is fixed.

However, I really want to be able to display columns on the entire row. I'd rather go back to column bar rendering over into gallery area than how it is currently.

**Comment by Taiko2k** [comment]
> I really want to be able to display columns on the entire row.

Could you elaborate? It makes no sense for the columns to render over the gallery right?

**Comment by StrangeSeasOfThought** [comment]
> Could you elaborate? It makes no sense for the columns to render over the gallery right?

That's right. But that's only momentarily, it's not like I keep it like that. Should I ever move the columns too far to the right, I can immediately move them back again.
And it's not like I have to change the columns often.
My issue is with the truncating.

**Comment by StrangeSeasOfThought** [comment]
> Edit: I found the issue now, truncating _should_ be fixed now on latest commit

Instead of rendering over the gallery, the columns just disappear now and there seems to be no way to get them back.

**Comment by Taiko2k** [comment]
Okay, I've reverted some behavior. Columns wont be *rendered* over the gallery, but they will still persist and come back if you make room for them again.

**Comment by StrangeSeasOfThought** [comment]
That works and solves my issue with truncating, but I don't think it's an ideal solution either...

You usually don't want to add to the right click columns bar menu... but some music players and other apps often have an option there to set columns width automatically/stretch columns to fit, or something along the lines.

**Comment by Taiko2k** [comment]
Ive added a function "Auto Resize", on clicking will redistribute the sizes, which should help.
