### ISSUE TITLE
Provide a snap package WIP

### ISSUE THREAD

**Issue by brunob** [Taiko2k/TauonMusicBox#207]
As discussed in https://github.com/Taiko2k/TauonMusicBox/issues/201#issuecomment-554905788 and to follow #55 & #154 i'm trying to make a snap package of Tauon :)

I've started to work on this here https://github.com/brunob/TauonMusicBox/blob/snapcraft/snapcraft.yaml

For now, i'm providing the snap recipe directly in the repo of the app, but i can switch it to a dedicated repo and getting git source directly form the snap build, which way do you prefer @Taiko2k ?

The snap recipe builds well, but i get the following error when starting the app. The problem is related to `PYSDL2_DLL_PATH`.

I've read some issues about this type of error in the repo, especially https://github.com/Taiko2k/TauonMusicBox/issues/3#issuecomment-261713125 & https://github.com/Taiko2k/TauonMusicBox/issues/6#issuecomment-348718254 but i can't find the related fixes.

```
Traceback (most recent call last):
  File "/snap/tauon/x2/lib/python3.6/site-packages/sdl2/dll.py", line 113, in <module>
    dll = DLL("SDL2", ["SDL2", "SDL2-2.0"], os.getenv("PYSDL2_DLL_PATH"))
  File "/snap/tauon/x2/lib/python3.6/site-packages/sdl2/dll.py", line 54, in __init__
    (libinfo, dllmsg))
RuntimeError: could not find any library for SDL2 (PYSDL2_DLL_PATH: unset)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/tauon/x2/tauon.py", line 377, in <module>
    from sdl2 import *
  File "/snap/tauon/x2/lib/python3.6/site-packages/sdl2/__init__.py", line 2, in <module>
    from .dll import get_dll_file, _bind
  File "/snap/tauon/x2/lib/python3.6/site-packages/sdl2/dll.py", line 115, in <module>
    raise ImportError(exc)
ImportError: could not find any library for SDL2 (PYSDL2_DLL_PATH: unset)
```
Does anyone could give me some hints for fixing the bug with `os.getenv("PYSDL2_DLL_PATH")` ?

**Comment by Taiko2k** [comment]
> The problem is related to PYSDL2_DLL_PATH.

Yes that's where I got stuck also. Would likely be that the underlying `ctypes.util.find_library` function is not finding (or accepting) the SDL2 library files.

So it would *seem* that the solution is to set the environment variable `PYSDL2_DLL_PATH` to the path of the library files (from the perspective of the snapped application). Or setting `LD_LIBRARY_PATH` might also work.

Also, I think we might need to follow the steps here to allow opengl https://forum.snapcraft.io/t/adding-opengl-gpu-support-to-a-snap/6273 (possibly related to the above problem?)

>  but i can switch it to a dedicated repo and getting git source directly form the snap build, which way do you prefer @Taiko2k ?

I don't suppose it makes much difference. Its fine as it is for now.

**Comment by brunob** [comment]
'k, thx for the answer, i've found a post mentioning the bug here https://forum.snapcraft.io/t/issue-when-snap-uses-pythons-ctype-util-find-library/9690 i'll post there to ask if there is an update about this.

**Comment by brunob** [comment]
@Taiko2k going further on this, i've signaled the issue with pysdl2 on their repo. 

I've updated my snap recipe to stage some needed packages that are not referenced in the wiki, ans now i get this error which freeze my system when starting the app (got to kill -9 the process) :

```
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: MESA-LOADER: failed to retrieve device information
Using SDL version: 2.0.8
Using GStreamer as fallback. Some functions disabled
Config reload theme...
Applying external theme: Sky
Theme number: 7
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/snap/tauon/x9/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/snap/tauon/x9/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/snap/tauon/x9/t_modules/t_gstreamer.py", line 499, in player3
    player = GPlayer()
  File "/snap/tauon/x9/t_modules/t_gstreamer.py", line 82, in __init__
    prefs.gst_output, ghost_unlinked_pads=True)
GLib.GError: gst_parse_error: no element "pulsesink" (1)
```

**Comment by brunob** [comment]
\o/ i finally have a working snap of tauon that can play music (minus the fact i have to manually patch dll.py in pysdl2, i'll look to automate this in the snap until a newer release of pysdl2 fixing the bug).

Now i have to test the network function (get cover arts, etc), and after that we can request register the tuaon name on snapcraft.io :)

**Comment by Taiko2k** [comment]
Also other things we'd want to test:

- Mpris working?
- Mediakeys working?
- Drag and drop file importing (from outside home also?)
- Open folder / Open image (can we call xdg-open?)
- Edit with Picard / Transcoding with FFMPEG (can we call other applications?)
- Discord IPC (low priority)

**Comment by brunob** [comment]
Sure :)

- [ ]     Mpris working?

- [ ]     Mediakeys working? (Gnome dbus)

- [x]     Drag and drop file importing (from outside home also?)

A dragndrop from home/music/test_album works, but show the error dialog "Permission error accessing on or more folder" despite the presence of `removable-media` in the snap recipe, have to fix that

- [x]     Open folder / Open image (can we call xdg-open?)

App ask for permission on this and it works, have to find what i need to do to authorize it by default

- [ ]     Edit with Picard / Transcoding with FFMPEG (can we call other applications?)

- [ ]     Discord IPC

- [ ]     Locale detection for translations. For example, does having LANG="ja.UTF-8" (not sure if that's right) switch the UI language? (Will need to have run compile-translations.py before building)

**Comment by Taiko2k** [comment]
> This should work out the box & i'm seeing `Locale detected: fr_FR + No translation file available`

Yep that sounds like its working.

> and after that we can request register the tauon name on snapcraft.io

Okay I've registered a name. If you give me an email address I can add you as a collaborator.

> see brunob@3eab3de

I'm trying to build that latest change, but still getting the `could not find any library for SDL2` error. Not sure if I'm doing something wrong. My process was `git pull`, `snapcraft clean`, `snapcraft`, `sudo snap install tauon_0+git.3eab3de-dirty_amd64.snap`, then `snap run tauon`. Also not sure why it says dirty? Am I missing a step?

**Comment by brunob** [comment]
> Okay I've registered a name. If you give me an email address I can add you as a collaborator.

Nice, this my email bruno at eliaz.fr

> I'm trying to build that latest change, but still getting the could not find any library for SDL2 error. 

My bad, i've fixed it with latest commit on snapcraft branch, ftr you can also try it with : `snapcraft try` + `snap try prime` and finally launch `tauon`.

> This might be preferable actually, since then one can build with just the snapcraft file.

And it will allow us to use build.snapcraft.io (but it may work as it is, have to test). Anyway, if you prefer a repo containing only the snap recipe as i do there https://github.com/thetimelineproj/timeline_snap/ i have to extract the file and his history to a new repo.

> Also what are libgpm2 and libslang2 for? I notice these are GPLv2 but Tauon shouldn't have any GPL dependencies.

These libs are needed since i got errors if they are not present. Just out of curiosity, why Tauon shouldn't have any GPL deps since it released on the same license ?

**Comment by Taiko2k** [comment]
> Just out of curiosity, why Tauon shouldn't have any GPL deps since it released on the same license ?

Since Tauon still *links* with closed-source BASS, its not fully GPL compatible. I think this situation with those libraries should be fine since Tauon doesn't link to them.

> Why not, but since we may use build.snapcraft.io it can work as it is or with snap recipe in a specific repo. Anyway, if you prefer a repo containing only the snap recipe as i do there https://github.com/thetimelineproj/timeline_snap/ i have to extract the file and his history to a new repo.

I assumed one way might have been better, I actually don't know.

> My bad, i've fixed it with latest commit on snapcraft branch.

Seems I'm still encountering that same error.

**Comment by brunob** [comment]
> I assumed one way might have been better, I actually don't know.

It depends only of your preference, one specific repo for the snap yaml, or putting the snap yaml in the main repo (imho it's simpler to put it in the main repo). 

I've merged the snapcraft branch in master on my fork, and build.snapcraft.io is happy with that, i can build the snap.

> Seems I'm still encountering that same error.

I'm sure you have updated your local copy, so as is said you just have to launch tauon after snap try prime (snap run tauon will launch the past install). You can verify my fix is well applied with `ll prime/usr/lib/x86_64-linux-gnu/libSDL2*` which should list the wylinks created on prime stage by `override-prime` stage https://github.com/brunob/TauonMusicBox/blob/snapcraft/snapcraft.yaml#L72

Anyway, if you're ok with that, i can produce a test build from build.snapcraft.io connected to my fork, and keep this one private for now to allow us to test it in real conditions.

**Comment by Taiko2k** [comment]
I did the `snapcraft try`, `snap try prime` then `tauon`. But those links don't appear to be in `prime/usr/lib/x86_64-linux-gnu/`. Manually creating them does then fix the error.
___

I'm then hitting a new dbus related error, though its likely a bug in Tauon. It's not finding "gnome settings daemon", but that makes sense perhaps with this being tested on Ubuntu 18.04 (unity). 

Though it does seem to be being blocked from accessing the interface anyway. `An AppArmor policy prevents this sender from sending this message to this recipient`

```
BASS not found
ERROR:dbus.proxies:Introspect error on :1.44:/org/gnome/SettingsDaemon/MediaKeys: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.80" (uid=1000 pid=5781 comm="tauonmb                         " label="snap.tauon.tauon (enforce)") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination=":1.44" (uid=1000 pid=2373 comm="/usr/lib/gnome-settings-daemon/gsd-media-keys " label="unconfined")
Could not connect to gnome media keys
Using SDL version: 2.0.8
Using GStreamer as fallback. Some functions disabled
Traceback (most recent call last):
  File "/snap/tauon/x3/tauon.py", line 30098, in <module>
    gnome.focus()
  File "/snap/tauon/x3/t_modules/t_dbus.py", line 39, in focus
    dbus_interface=dbus_interface)
  File "/snap/tauon/x3/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/snap/tauon/x3/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.InvalidArgs: Type of message, '(si)', does not match expected type '(su)'
```

Ive pushed a fix to catch the error. 

Finally then I can get Tauon to run.

**Comment by brunob** [comment]
Nice, i think we can merge the snap for now in order to test the build with snapcraft.io, i'll send the PR now.

**Comment by brunob** [comment]
Damn, i got an error when trying to build from my master branch which is up to date with yours, cf :

```
ERROR: Could not find a version that satisfies the requirement setproctitle (from -r /root/parts/python-deps/build/requirements.txt (line 14)) (from versions: none)
ERROR: No matching distribution found for setproctitle (from -r /root/parts/python-deps/build/requirements.txt (line 14))
```

**Comment by Taiko2k** [comment]
> I did the snapcraft try, snap try prime then tauon.

I've just tried this in a fresh VM (Ubuntu 18.04), still not working, so I'm sure something is up.

___

Ive done some more testing:

- [x] Gstreamer Playback
- [ ] BASS Playback | **Not working**. I think we need the pulseaudio-alsa package. (So pulseaudio appears as an alsa device. (BASS only supports alsa))
- [x] MPRIS | Working
- [ ] Mediakeys | **AccessDenied** `/org/gnome/SettingsDaemon/MediaKeys: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied`
- [x] XDG-Open | Working, but asks for confirmation every time. Is there a way to bypass this? Either by default or user override?
- [ ] Other apps | **Not working**. Is there a way we can list and run user installed apps? On the Flatpak side I provide a command to override the permission for this to the user. For FFMPEG I bundle this in the Flatpak. Perhaps we could do that here also? There's also Picard to consider.
- [x] Webserver | Appears to be working.

Btw, could we add `unrar` and `p7zip-full` to the stage-packages? (And have them show in PATH?)

Also, will we support JACK with GStreamer? If not ill just add an exception as to not list this in the snap version.

**Comment by brunob** [comment]
> I've just tried this in a fresh VM (Tested with Ubuntu 18.04 and 19.04), still not working, so I'm sure something is up.

Can you please plug the repo to build system from https://build.snapcraft.io/ and launch a build manually ? (i can't do it since i have no permission on the repo)

> I've just tried this in a fresh VM (Tested with Ubuntu 18.04 and 19.04), still not working, so I'm sure something is up.

I'll try to install the snap from snapcraft.io once the build will be done on another system with ubuntu 18.04 (my daily machine is on ubuntu 16.04).

----

> Mediakeys | AccessDenied

I'll look to this.

> XDG-Open

Same, i'll try to find a way to make it permanent, maybe this can be achieved once the snap is installed form the store.

> Other apps

Will look too.

> I've added the following stage-packages: picard ffmpeg unrar p7zip-full flac

Not sure we need this if we find a way to "connect these apps from the snap.

**Comment by Taiko2k** [comment]
> Can you please plug the repo to build system from https://build.snapcraft.io/ and launch a build manually ? 

Okay

> Not sure we need this if we find a way to "connect these apps from the snap.

This might be ideal since the version of Picard included in 18.04 is rather old. Even if it needs manual user override, would be preferable. 

Though probably no reason not to simply include the others.

**Comment by brunob** [comment]
> I did the snapcraft try, snap try prime then tauon. But those links don't appear to be in prime/usr/lib/x86_64-linux-gnu/. Manually creating them does then fix the error.

This should be fixed with #212 :)

**Comment by brunob** [comment]
@Taiko2k you may have a look at https://snapcraft.io/docs/alsa-interface & https://snapcraft.io/docs/t/the-jack1-interface/13093

**Comment by brunob** [comment]
From my test, the notification of song change doesn't work, maybe we can get it by adding `libnotify4` to stage-packages as done https://github.com/videolan/vlc/blob/master/extras/package/snap/snapcraft.yaml#L217 & https://git.2li.ch/various/Google-Play-Music-Desktop-Player/commit/50e2d3114e31e56ea492d93ee5d74ce0dafc3969

**Comment by Taiko2k** [comment]
> the notification of song change doesn't work

Seems to work for me. Note that the intended behavior is that track change notifications are not sent if the window is currently focused.

**Comment by brunob** [comment]
@Taiko2k FTR the XDG-Open dialog could not be accepted one time for all cf :

https://forum.snapcraft.io/t/allowing-xdg-open-to-open-files/3789/13
https://forum.snapcraft.io/t/snap-how-to-grant-permament-permission-to-read-folder/7257/3

**Comment by Taiko2k** [comment]
The snap build was failing automatic review due to the section:

```
slots:
  dbus-tauon:
    interface: dbus
    name: org.mpris.MediaPlayer2.tauon
    bus: session
```

So I've removed this. Seems to work fine without it.

**Comment by brunob** [comment]
'k, i'll post on the forum to find why this entry was blocking and how can we get mediakeys working.

**Comment by brunob** [comment]
For the dbus problem with review, i think you can put it back and we will request a manual review as stated here https://forum.snapcraft.io/t/manual-review-firefox/14460/2

**Comment by Taiko2k** [comment]
> For the dbus problem

I think it works automatically if the snap name matches the dbus name for mpris, as it does here. So it might not be necessary.

**Comment by brunob** [comment]
Nice, so the mediakeys works now or should i post in the forum to ask help about it ?

**Comment by Taiko2k** [comment]
> Nice, so the mediakeys works now or should i post in the forum to ask help about it ?

I was just refering to mpris. The Mediakeys use a different dbus path (gnome settings daemon). So yeah ask about it.

If you try run the snap you should see the error.

**Comment by Taiko2k** [comment]
Oh... actually *do* seem to be working. That error is unrelated

**Comment by brunob** [comment]
Cool, i'm installing latest build from the store in order to test it again. What do we have to do before release it publicly ?

I think we can push more screenshots (the one present in the readme are nicer than the one here https://dashboard.snapcraft.io/snaps/tauon/).

**Comment by Taiko2k** [comment]
Okay I've uploaded some more screenshots.

I think that's all the major things covered. I'll release tauon **v5.1.2** within the next day or so and release the snap at the same time.

**Comment by brunob** [comment]
(y)

**Comment by Taiko2k** [comment]
Oh, we don't have a desktop launcher (and icons) exported. Do you know how to do this?

Related files are in the /extra folder. Think we may need to create a new desktop file from `tauonmb.desktop` since that one uses a fixed path for launching.

**Comment by brunob** [comment]
Strange, cause when i was testing local build with `snapcrat try` or installing it before the merge, i had the icon of the app in my dock when i launched it. Now i don't have it if i install it from the edge channel.

For the timeline snap i've put the desktop file in a `gui` folder as this https://github.com/thetimelineproj/timeline_snap/tree/master/snap/gui

We may achieve it without providing a specific desktop file by adapting the one provided in extra folder and moving the files to the right place in `override-build` of tauon part https://github.com/Taiko2k/TauonMusicBox/blob/master/snapcraft.yaml#L87

**Comment by Taiko2k** [comment]
Okay got the desktop file working. 

I've set the store page public now.

**Comment by Taiko2k** [comment]
I'll close this now. We can open again if any issues arise. Thanks for putting in the time to help get this working!

**Comment by brunob** [comment]
Yes, i also think it's time to close this one, on dedicated issue per bug is better for the future.

U're welcome, **thx to you** for this great player that works exactly as what i'm looking for :)

**Comment by Taiko2k** [comment]
@brunob 

Latest builds don't seem to be working now.

From trying to launch from edge channel:

```Traceback (most recent call last):
  File "/snap/tauon/89/tauon.py", line 298, in <module>
    from sdl2 import *
  File "/snap/tauon/89/lib/python3.6/site-packages/sdl2/__init__.py", line 2, in <module>
    from .dll import get_dll_file, _bind
  File "/snap/tauon/89/lib/python3.6/site-packages/sdl2/dll.py", line 223, in <module>
    dll = DLL("SDL2", ["SDL2", "SDL2-2.0"], os.getenv("PYSDL2_DLL_PATH"))
  File "/snap/tauon/89/lib/python3.6/site-packages/sdl2/dll.py", line 101, in __init__
    foundlibs = _findlib(libnames, path)
  File "/snap/tauon/89/lib/python3.6/site-packages/sdl2/dll.py", line 68, in _findlib
    files = os.listdir(path)
FileNotFoundError: [Errno 2] No such file or directory: ':/snap/tauon/89/usr/lib/x86_64-linux-gnu'
```
Could you look into this?

**Comment by brunob** [comment]
@Taiko2k 'k, i'll try to look at this asap.

**Comment by Taiko2k** [comment]
Seemed to be related to a recent `pysdl2` update. Holding it back at `0.9.6` in the requirements.txt works. So I'm able to release to stable again now.

**Comment by brunob** [comment]
@Taiko2k maybe it's our patch for handling old pysdl2 bug that generate this ? don't think so, but maybe... cf https://github.com/Taiko2k/TauonMusicBox/pull/212/files

FTR, the bug was https://github.com/marcusva/py-sdl2/issues/148 and had been fixed by https://github.com/marcusva/py-sdl2/commit/3cc7218ec092e24bdf9f9dc0d4e38affe1e28a84#diff-83f1203383bf3ea37ff4b20e5149bc76

Reading the error you posted, it seems that you don't have `/usr/lib/x86_64-linux-gnu` in the snap, which is defined from here https://github.com/Taiko2k/TauonMusicBox/blob/master/snapcraft.yaml#L23

What system are you using when this error is throwed ?

**Comment by Taiko2k** [comment]
@brunob I was testing on Ubuntu 19.04. Pysdl2 0.9.7 fails with that error, while the previous 0.9.6 works, nothing else is changed. `/snap/usr/lib/x86_64-linux-gnu` appears to exist.

Could it be that colon there causing it to fail? `':/snap/` , from `PYSDL2_DLL_PATH: $PYSDL2_DLL_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET`? I'm not sure how thats supposed to work.

**Comment by a-hurst** [comment]
@brunob @Taiko2k Hi there, pysdl2 maintainer here: yep, the colon is the issue. The `PYSDL2_DLL_PATH` variable is only expected to contain a single path, and doesn't support Bash-style specifying of multiple paths in the order you want them to be searched.

Is it useful for your project to be able to set multiple DLL paths? If so, I can try and implement support for it. I know some OSes support colons in file/folder names, so that's the only major complication I can see.

**Comment by Taiko2k** [comment]
@a-hurst  Oh... so that's what the colon does. So that `PYSDL2_DLL_PATH:` bit isn't really needed, I can just leave it as the full single path and it'll work.

That's all that matters so I guess your proposed change isn't necessary here.

**Comment by brunob** [comment]
@Taiko2k sorry for not answering here, i'm a bit far away from snap's things these days... I've seen your commit about this 58437f66e6c0bc4a979f66e7a79761e6feed62f3 does it fix the bug or do you need help or testing ?

**Comment by Taiko2k** [comment]
@brunob Indeed it does seem to be fixed with that commit.

**Comment by brunob** [comment]
@Taiko2k (y)
