### ISSUE TITLE
Unable to import remote files via NFS

### ISSUE THREAD

**Issue by mannp** [Taiko2k/TauonMusicBox#491]
Using Arch linux to connect to a linux file server via NFS and Tauon is unable to import any files.

It complains at no files being present but the files are there and readable.

The same files shared via SMB work fine.

**Comment by Taiko2k** [comment]
Do you get any error message? If so what does it specifically say?

**Comment by mannp** [comment]
> file to import missing
> Writing database to disk.

**Comment by Taiko2k** [comment]
The files would need to be mounted on the filesystem. I.e. can you navigate to and list the files using the `ls` command in terminal?

**Comment by mannp** [comment]
Well yes of course, they are mounted on the filesystem

> ❯ ls  '/run/user/1000/gvfs/nfs:host=<file server>,prefix=%2Fmnt%2Fuser%2FMy_Data/MusicTagged/FLAC'
> 'Album Artists'   Extra   infobrowser.opml   Singles  'Various Artists'

Is it the same destination as mounted via smb but tauon doesn't find the files///as though is is not going into directories like it does with smb.

**Comment by Taiko2k** [comment]
It could be the path is being parsed wrongly. That mount point does look kinda scary.

Try edit `tauon.py`, search for the line that contains "file to import missing", and below that insert the line `print(path)`.  Then save and rerun, try to see mport that same flac file again, I assume the path it prints might not match.

**Comment by mannp** [comment]
Arch mounts as -> /run/user/1000/gvfs//nfs:host=<server>,prefix=%2Fmnt%2Fuser%2FMy_Data/MusicTagged/MP3

Tauon reports;

> /run/user/1000/gvfs/nfs:host=<server>,prefix=/mnt/user/My_Data/MusicTagged/MP3

**Comment by Taiko2k** [comment]
Okay so it looks like there are urlencoded characters in that URI, and tauon currently attempts to decode any and all found. But its not intended that those ones are to be decoded because it's litterally part of the URI.

Hmm, probably tauon shouldn't do that for plain paths like that... Yeah, I suppose that should be fixed.

In the mean time, you could create a symlink to that folder but one with a simpler path. Or what I would do is use something else to mount the NFS, like mount it using fstab (say mount it to /mnt/something) for example rather than using gvfs.

**Comment by mannp** [comment]
Its decoded correctly for the same share via smb, so it seems to not be any complexity of share being the problem.

Symlinks got me going again, as don't like fstab mounts.

Thanks.

**Comment by C0rn3j** [comment]
Presuming this is still an issue today, I'm down to fix this but I need someone to provide me a problematic NFS server or dead-simple instructions to spin it up on Docker/Incus, as I am interested in fixing this bug but not figuring out NFS-specific setup issues.

EDIT: I attempted to take a stab at this, but noticed that to mount NFS via GVFS fuse I'd need to use NFSv3 since NFSv4 is not supported - https://gitlab.gnome.org/GNOME/gvfs/-/merge_requests/13 - and I already have v4 running on my server.

One solution would be not using FUSE to mount your NFS mounts.
