### ISSUE TITLE
When importing music folder with .cue on Windows track's file doesn't filter out

### ISSUE THREAD

**Issue by Mario32ru** [Taiko2k/TauonMusicBox#885]
![cue import bug](https://user-images.githubusercontent.com/7543646/204925938-929cde32-0f43-4e9e-bbbf-89791e80294f.png)

**Comment by Taiko2k** [comment]
Was it that you tried to drag and drop both files (including the audio file and the CUE) simultaneously? (as opposed to a folder)? For this situation I've now committed a fix.

**Comment by Mario32ru** [comment]
Only happens when importing music folder. Dropping folder with the album or selecting both .cue and .flac files and dragging them into playlist does filter the track's file. Are you gonna release new version soon? If not i can build master to test your commit.

**Comment by Mario32ru** [comment]
I tested drag and drop more and found that if you select both files and drag .flac file then the last track duplicates, but if you drag .cue file then track's file filters out.
![cue drag and drop bug](https://user-images.githubusercontent.com/7543646/205035231-53a41ea1-5d94-479a-805a-19c57cdb45c0.png)
On Linux with gnome Files it duplicates in both cases.
Also on Linux the same album imports from music folder just fine.

**Comment by C0rn3j** [comment]
Is this still a problem on Tauon 7.9.0+ and current SW versions?

**Comment by Mario32ru** [comment]
Tested 7.9.0 and c7f1183 on Window 11, still present.
No bug on Debian with Sway and Dolphin, flatpak 7.9.0.

**Comment by C0rn3j** [comment]
I can probably take a look at this at some point, could you hop over to Discord and DM me the files + exact repro steps?

**Comment by C0rn3j** [comment]
If you could drop the files that reproduce the issue here, that'd be neat - https://cloud.rys.rs/s/g82Yb52ifx53wHy
